export const mockCardData = [
  {
    id: 1,
    bannerImageUrl: 'https://picsum.photos/300/200?random=1',
    title: '패러글라이딩 체험',
    rating: 4.5,
    reviewCount: 123,
    currencySymbol: '₩',
    price: 35000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 1'),
  },
  {
    id: 2,
    bannerImageUrl: 'https://picsum.photos/300/200?random=2',
    title: '제주도 요트 투어',
    rating: 4.8,
    reviewCount: 89,
    currencySymbol: '₩',
    price: 45000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 2'),
  },
  {
    id: 3,
    bannerImageUrl: 'https://picsum.photos/300/200?random=3',
    title: '양떼목장 체험',
    rating: 4.2,
    reviewCount: 57,
    currencySymbol: '₩',
    price: 30000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 3'),
  },
  {
    id: 4,
    bannerImageUrl: 'https://picsum.photos/300/200?random=4',
    title: '한강 자전거 투어',
    rating: 4.6,
    reviewCount: 70,
    currencySymbol: '₩',
    price: 25000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 4'),
  },
  {
    id: 5,
    bannerImageUrl: 'https://picsum.photos/300/200?random=5',
    title: '전통 한옥 스테이',
    rating: 4.9,
    reviewCount: 150,
    currencySymbol: '₩',
    price: 80000,
    priceUnit: '1박',
    onClick: () => alert('Clicked 5'),
  },
  {
    id: 6,
    bannerImageUrl: 'https://picsum.photos/300/200?random=7',
    title: '열기구 체험',
    rating: 4.7,
    reviewCount: 95,
    currencySymbol: '₩',
    price: 55000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 7,
    bannerImageUrl: 'https://picsum.photos/300/200?random=8',
    title: '놀이공원',
    rating: 4.9,
    reviewCount: 95,
    currencySymbol: '₩',
    price: 51000,
    priceUnit: '2인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 8,
    bannerImageUrl: 'https://picsum.photos/300/200?random=9',
    title: '아쿠아리움',
    rating: 4.7,
    reviewCount: 95,
    currencySymbol: '₩',
    price: 80000,
    priceUnit: '4인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 9,
    bannerImageUrl: 'https://picsum.photos/300/200?random=10',
    title: '승마 체험',
    rating: 4.7,
    reviewCount: 95,
    currencySymbol: '₩',
    price: 40000,
    priceUnit: '2인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 10,
    bannerImageUrl: 'https://picsum.photos/300/200?random=11',
    title: '템플스테이',
    rating: 4.7,
    reviewCount: 95,
    currencySymbol: '₩',
    price: 5000,
    priceUnit: '3인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 11,
    bannerImageUrl: 'https://picsum.photos/300/200?random=12',
    title: '도자기 체험',
    rating: 4.8,
    reviewCount: 96,
    currencySymbol: '₩',
    price: 30000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 6'),
  },
  {
    id: 12,
    bannerImageUrl: 'https://picsum.photos/300/200?random=12',
    title: '서핑 클래스',
    rating: 4.4,
    reviewCount: 85,
    currencySymbol: '₩',
    price: 60000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 12'),
  },
  {
    id: 13,
    bannerImageUrl: 'https://picsum.photos/300/200?random=13',
    title: '클라이밍 체험',
    rating: 4.6,
    reviewCount: 40,
    currencySymbol: '₩',
    price: 42000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 13'),
  },
  {
    id: 14,
    bannerImageUrl: 'https://picsum.photos/300/200?random=14',
    title: '바리스타 클래스',
    rating: 4.9,
    reviewCount: 67,
    currencySymbol: '₩',
    price: 35000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 14'),
  },
  {
    id: 15,
    bannerImageUrl: 'https://picsum.photos/300/200?random=15',
    title: '도보 역사 투어',
    rating: 4.3,
    reviewCount: 120,
    currencySymbol: '₩',
    price: 20000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 15'),
  },
  {
    id: 16,
    bannerImageUrl: 'https://picsum.photos/300/200?random=16',
    title: '캠핑 체험',
    rating: 4.5,
    reviewCount: 76,
    currencySymbol: '₩',
    price: 70000,
    priceUnit: '1박',
    onClick: () => alert('Clicked 16'),
  },
  {
    id: 17,
    bannerImageUrl: 'https://picsum.photos/300/200?random=17',
    title: '풍경 드로잉 클래스',
    rating: 4.6,
    reviewCount: 54,
    currencySymbol: '₩',
    price: 32000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 17'),
  },
  {
    id: 18,
    bannerImageUrl: 'https://picsum.photos/300/200?random=18',
    title: '도심 피크닉',
    rating: 4.2,
    reviewCount: 38,
    currencySymbol: '₩',
    price: 18000,
    priceUnit: '2인',
    onClick: () => alert('Clicked 18'),
  },
  {
    id: 19,
    bannerImageUrl: 'https://picsum.photos/300/200?random=19',
    title: '가죽 공예 체험',
    rating: 4.8,
    reviewCount: 63,
    currencySymbol: '₩',
    price: 38000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 19'),
  },
  {
    id: 20,
    bannerImageUrl: 'https://picsum.photos/300/200?random=20',
    title: '자연 속 요가 클래스',
    rating: 4.9,
    reviewCount: 92,
    currencySymbol: '₩',
    price: 40000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 20'),
  },
  {
    id: 21,
    bannerImageUrl: 'https://picsum.photos/300/200?random=21',
    title: '야간 별보기 캠핑',
    rating: 4.7,
    reviewCount: 45,
    currencySymbol: '₩',
    price: 55000,
    priceUnit: '1박',
    onClick: () => alert('Clicked 21'),
  },
  {
    id: 22,
    bannerImageUrl: 'https://picsum.photos/300/200?random=22',
    title: '한지 공예 클래스',
    rating: 4.4,
    reviewCount: 32,
    currencySymbol: '₩',
    price: 25000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 22'),
  },
  {
    id: 23,
    bannerImageUrl: 'https://picsum.photos/300/200?random=23',
    title: '도심 자전거 투어',
    rating: 4.3,
    reviewCount: 51,
    currencySymbol: '₩',
    price: 22000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 23'),
  },
  {
    id: 24,
    bannerImageUrl: 'https://picsum.photos/300/200?random=24',
    title: '비건 쿠킹 클래스',
    rating: 4.9,
    reviewCount: 73,
    currencySymbol: '₩',
    price: 47000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 24'),
  },
  {
    id: 25,
    bannerImageUrl: 'https://picsum.photos/300/200?random=25',
    title: '낚시 체험',
    rating: 4.1,
    reviewCount: 29,
    currencySymbol: '₩',
    price: 35000,
    priceUnit: '2인',
    onClick: () => alert('Clicked 25'),
  },
  {
    id: 26,
    bannerImageUrl: 'https://picsum.photos/300/200?random=26',
    title: '제과제빵 원데이 클래스',
    rating: 4.6,
    reviewCount: 88,
    currencySymbol: '₩',
    price: 39000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 26'),
  },
  {
    id: 27,
    bannerImageUrl: 'https://picsum.photos/300/200?random=27',
    title: '목공 체험',
    rating: 4.5,
    reviewCount: 40,
    currencySymbol: '₩',
    price: 42000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 27'),
  },
  {
    id: 28,
    bannerImageUrl: 'https://picsum.photos/300/200?random=28',
    title: '힐링 명상 워크숍',
    rating: 4.7,
    reviewCount: 62,
    currencySymbol: '₩',
    price: 30000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 28'),
  },
  {
    id: 29,
    bannerImageUrl: 'https://picsum.photos/300/200?random=29',
    title: '로컬 푸드 마켓 투어',
    rating: 4.2,
    reviewCount: 36,
    currencySymbol: '₩',
    price: 15000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 29'),
  },
  {
    id: 30,
    bannerImageUrl: 'https://picsum.photos/300/200?random=30',
    title: '수제 맥주 만들기',
    rating: 4.8,
    reviewCount: 49,
    currencySymbol: '₩',
    price: 48000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 30'),
  },
  {
    id: 31,
    bannerImageUrl: 'https://picsum.photos/300/200?random=31',
    title: '비건 디저트 클래스',
    rating: 4.6,
    reviewCount: 59,
    currencySymbol: '₩',
    price: 32000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 31'),
  },
  {
    id: 32,
    bannerImageUrl: 'https://picsum.photos/300/200?random=32',
    title: '캘리그라피 원데이',
    rating: 4.3,
    reviewCount: 34,
    currencySymbol: '₩',
    price: 21000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 32'),
  },
  {
    id: 33,
    bannerImageUrl: 'https://picsum.photos/300/200?random=33',
    title: '도심 요가 클래스',
    rating: 4.9,
    reviewCount: 85,
    currencySymbol: '₩',
    price: 38000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 33'),
  },
  {
    id: 34,
    bannerImageUrl: 'https://picsum.photos/300/200?random=34',
    title: '전통 염색 체험',
    rating: 4.5,
    reviewCount: 42,
    currencySymbol: '₩',
    price: 29000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 34'),
  },
  {
    id: 35,
    bannerImageUrl: 'https://picsum.photos/300/200?random=35',
    title: '천연비누 만들기',
    rating: 4.7,
    reviewCount: 64,
    currencySymbol: '₩',
    price: 26000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 35'),
  },
  {
    id: 36,
    bannerImageUrl: 'https://picsum.photos/300/200?random=36',
    title: '전통 차 시음 체험',
    rating: 4.2,
    reviewCount: 38,
    currencySymbol: '₩',
    price: 18000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 36'),
  },
  {
    id: 37,
    bannerImageUrl: 'https://picsum.photos/300/200?random=37',
    title: '베이킹 클래스',
    rating: 4.8,
    reviewCount: 96,
    currencySymbol: '₩',
    price: 37000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 37'),
  },
  {
    id: 38,
    bannerImageUrl: 'https://picsum.photos/300/200?random=38',
    title: '도심 보트 체험',
    rating: 4.4,
    reviewCount: 52,
    currencySymbol: '₩',
    price: 41000,
    priceUnit: '2인',
    onClick: () => alert('Clicked 38'),
  },
  {
    id: 39,
    bannerImageUrl: 'https://picsum.photos/300/200?random=39',
    title: '인디 밴드 공연 관람',
    rating: 4.6,
    reviewCount: 75,
    currencySymbol: '₩',
    price: 33000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 39'),
  },
  {
    id: 40,
    bannerImageUrl: 'https://picsum.photos/300/200?random=40',
    title: '도심 보드게임 모임',
    rating: 4.5,
    reviewCount: 48,
    currencySymbol: '₩',
    price: 22000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 40'),
  },
  {
    id: 41,
    bannerImageUrl: 'https://picsum.photos/300/200?random=41',
    title: '야외 수채화 클래스',
    rating: 4.6,
    reviewCount: 61,
    currencySymbol: '₩',
    price: 28000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 41'),
  },
  {
    id: 42,
    bannerImageUrl: 'https://picsum.photos/300/200?random=42',
    title: '지속가능한 농장 체험',
    rating: 4.7,
    reviewCount: 90,
    currencySymbol: '₩',
    price: 32000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 42'),
  },
  {
    id: 43,
    bannerImageUrl: 'https://picsum.photos/300/200?random=43',
    title: '사계절 꽃꽂이 클래스',
    rating: 4.8,
    reviewCount: 68,
    currencySymbol: '₩',
    price: 27000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 43'),
  },
  {
    id: 44,
    bannerImageUrl: 'https://picsum.photos/300/200?random=44',
    title: '천체 관측 체험',
    rating: 4.9,
    reviewCount: 88,
    currencySymbol: '₩',
    price: 50000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 44'),
  },
  {
    id: 45,
    bannerImageUrl: 'https://picsum.photos/300/200?random=45',
    title: '전통 음식 만들기',
    rating: 4.5,
    reviewCount: 72,
    currencySymbol: '₩',
    price: 36000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 45'),
  },
  {
    id: 46,
    bannerImageUrl: 'https://picsum.photos/300/200?random=46',
    title: '도심 속 러닝 크루',
    rating: 4.3,
    reviewCount: 54,
    currencySymbol: '₩',
    price: 12000,
    priceUnit: '1회',
    onClick: () => alert('Clicked 46'),
  },
  {
    id: 47,
    bannerImageUrl: 'https://picsum.photos/300/200?random=47',
    title: '사운드 힐링 클래스',
    rating: 4.6,
    reviewCount: 66,
    currencySymbol: '₩',
    price: 33000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 47'),
  },
  {
    id: 48,
    bannerImageUrl: 'https://picsum.photos/300/200?random=48',
    title: '수제 향수 만들기',
    rating: 4.7,
    reviewCount: 79,
    currencySymbol: '₩',
    price: 40000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 48'),
  },
  {
    id: 49,
    bannerImageUrl: 'https://picsum.photos/300/200?random=49',
    title: '비건 요리 클래스',
    rating: 4.9,
    reviewCount: 101,
    currencySymbol: '₩',
    price: 38000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 49'),
  },
  {
    id: 50,
    bannerImageUrl: 'https://picsum.photos/300/200?random=50',
    title: '마을 걷기 투어',
    rating: 4.4,
    reviewCount: 47,
    currencySymbol: '₩',
    price: 16000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 50'),
  },
  {
    id: 51,
    bannerImageUrl: 'https://picsum.photos/300/200?random=51',
    title: '친환경 마켓 체험',
    rating: 4.3,
    reviewCount: 33,
    currencySymbol: '₩',
    price: 10000,
    priceUnit: '1회',
    onClick: () => alert('Clicked 51'),
  },
  {
    id: 52,
    bannerImageUrl: 'https://picsum.photos/300/200?random=52',
    title: '미니 정원 만들기',
    rating: 4.6,
    reviewCount: 44,
    currencySymbol: '₩',
    price: 24000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 52'),
  },
  {
    id: 53,
    bannerImageUrl: 'https://picsum.photos/300/200?random=53',
    title: '크로키 드로잉 체험',
    rating: 4.5,
    reviewCount: 61,
    currencySymbol: '₩',
    price: 28000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 53'),
  },
  {
    id: 54,
    bannerImageUrl: 'https://picsum.photos/300/200?random=54',
    title: '도심 속 자연 관찰',
    rating: 4.2,
    reviewCount: 39,
    currencySymbol: '₩',
    price: 14000,
    priceUnit: '1회',
    onClick: () => alert('Clicked 54'),
  },
  {
    id: 55,
    bannerImageUrl: 'https://picsum.photos/300/200?random=55',
    title: '감성 사진 스냅투어',
    rating: 4.8,
    reviewCount: 83,
    currencySymbol: '₩',
    price: 45000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 55'),
  },
  {
    id: 56,
    bannerImageUrl: 'https://picsum.photos/300/200?random=56',
    title: '일러스트 강의',
    rating: 4.6,
    reviewCount: 71,
    currencySymbol: '₩',
    price: 39000,
    priceUnit: '1인',
    onClick: () => alert('Clicked 56'),
  },
  {
    id: 57,
    bannerImageUrl: 'https://picsum.photos/300/200?random=57',
    title: '사계절 등산 체험',
    rating: 4.3,
    reviewCount: 50,
    currencySymbol: '₩',
    price: 26000,
    priceUnit: '1회',
    onClick: () => alert('Clicked 57'),
  },
  {
    id: 58,
    bannerImageUrl: 'https://picsum.photos/300/200?random=58',
    title: '전통 부채 만들기',
    rating: 4.7,
    reviewCount: 55,
    currencySymbol: '₩',
    price: 30000,
    priceUnit: '1인',
    category: '문화 · 예술',

    onClick: () => alert('Clicked 58'),
  },
  {
    id: 59,
    bannerImageUrl: 'https://picsum.photos/300/200?random=59',
    title: '나무공예 목걸이 만들기',
    rating: 4.6,
    reviewCount: 49,
    currencySymbol: '₩',
    price: 27000,
    priceUnit: '1인',
    category: '문화 · 예술',

    onClick: () => alert('Clicked 59'),
  },
  {
    id: 60,
    bannerImageUrl: 'https://picsum.photos/300/200?random=60',
    title: '야간 성곽길 산책',
    rating: 4.4,
    reviewCount: 58,
    currencySymbol: '₩',
    price: 17000,
    priceUnit: '1인',
    category: '문화 · 예술',
    onClick: () => alert('Clicked 60'),
  },
];
